# fly.toml app configuration file generated for docker-minecraft-server-hli15a on 2026-06-09T23:35:22Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-minecraft-server-hli15a'
primary_region = 'ord'

[build]

[[mounts]]
  source = 'data'
  destination = '/data'

[http_service]
  internal_port = 25565
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 8192
