#!/bin/bash

. ${SCRIPTS:-/}start-utils

if [ -d /plugins ]; then
  case ${TYPE} in
    SPIGOT|BUKKIT|PAPER)
      mkdir -p /data/plugins
      log "Copying plugins over..."
      # Copy plugins over using rsync to allow deeply nested updates of plugins
      # only updates files if the source file is newer and print updated files
      rsync -a --out-format="update:%f:Last Modified %M" --prune-empty-dirs --update /plugins /data
      ;;
  esac
fi

exec ${SCRIPTS:-/}start-finalSetupServerProperties $@
