#!/bin/bash

set -e

. ${SCRIPTS:-/}start-utils

#  CURSE_URL_BASE used in manifest downloads below
CURSE_URL_BASE=${CURSE_URL_BASE:-https://minecraft.curseforge.com/projects}

# Remove old mods/plugins
if [ "$REMOVE_OLD_MODS" = "TRUE" ]; then
  if [ "$TYPE" = "SPIGOT" ]; then
    rm -rf /data/plugins/*
  else
    rm -rf /data/mods/*
  fi
fi

# If supplied with a URL for a modpack (simple zip of jars), download it and unpack
if [[ "$MODPACK" ]]; then
EFFECTIVE_MODPACK_URL=$(curl -Ls -o /dev/null -w %{url_effective} $MODPACK)
case "X$EFFECTIVE_MODPACK_URL" in
  X[Hh][Tt][Tt][Pp]*.zip)
    log "Downloading mod/plugin pack via HTTP"
    log "  from $EFFECTIVE_MODPACK_URL ..."
    if ! curl -sSL -o /tmp/modpack.zip "$EFFECTIVE_MODPACK_URL"; then
      log "ERROR: failed to download from $EFFECTIVE_MODPACK_URL"
      exit 2
    fi

    if [ "$TYPE" = "SPIGOT" ]; then
      mkdir -p /data/plugins
      if ! unzip -o -d /data/plugins /tmp/modpack.zip; then
        log "ERROR: failed to unzip the modpack from $EFFECTIVE_MODPACK_URL"
      fi
    else
      mkdir -p /data/mods
      if ! unzip -o -d /data/mods /tmp/modpack.zip; then
        log "ERROR: failed to unzip the modpack from $EFFECTIVE_MODPACK_URL"
      fi
    fi
    rm -f /tmp/modpack.zip
    ;;
  *)
    log "Invalid URL given for modpack: Must be HTTP or HTTPS and a ZIP file"
    ;;
esac
fi

# If supplied with a URL for a plugin download it.
if [[ "$MODS" ]]; then
for i in ${MODS//,/ }
do
  EFFECTIVE_MOD_URL=$(curl -Ls -o /dev/null -w %{url_effective} $i)
  case "X$EFFECTIVE_MOD_URL" in
    X[Hh][Tt][Tt][Pp]*.jar)
      log "Downloading mod/plugin via HTTP"
      log "  from $EFFECTIVE_MOD_URL ..."
      if ! curl -sSL -o /tmp/${EFFECTIVE_MOD_URL##*/} $EFFECTIVE_MOD_URL; then
        log "ERROR: failed to download from $EFFECTIVE_MOD_URL to /tmp/${EFFECTIVE_MOD_URL##*/}"
        exit 2
      fi

      if [ "$TYPE" = "SPIGOT" ]; then
        mkdir -p /data/plugins
        mv /tmp/${EFFECTIVE_MOD_URL##*/} /data/plugins/${EFFECTIVE_MOD_URL##*/}
      else
        mkdir -p /data/mods
        mv /tmp/${EFFECTIVE_MOD_URL##*/} /data/mods/${EFFECTIVE_MOD_URL##*/}
      fi
      rm -f /tmp/${EFFECTIVE_MOD_URL##*/}
      ;;
    *)
      log "Invalid URL given for modpack: Must be HTTP or HTTPS and a JAR file"
      ;;
  esac
done
fi

if [[ "$MANIFEST" ]]; then
    if [[ -e "$MANIFEST" ]]; then
        EFFECTIVE_MANIFEST_FILE=$MANIFEST
    elif isURL "$MANIFEST"; then
        EFFECTIVE_MANIFEST_FILE=/tmp/manifest.json
        EFFECTIVE_MANIFEST_URL=$(curl -Ls -o /dev/null -w %{url_effective} $MANIFEST)
        curl -Ls -o $EFFECTIVE_MANIFEST_FILE "$EFFECTIVE_MANIFEST_URL"
    else
        log "MANIFEST='$MANIFEST' is not a valid manifest url or location"
        exit 2
    fi

case "X$EFFECTIVE_MANIFEST_FILE" in
  X*.json)
    if [ -f "${EFFECTIVE_MANIFEST_FILE}" ]; then
      MOD_DIR=${FTB_BASE_DIR:-/data}/mods
      if [ ! -d "$MOD_DIR" ]
      then
        log "Creating mods dir $MOD_DIR"
        mkdir -p "$MOD_DIR"
      fi
      log "Starting manifest download..."
      cat "${EFFECTIVE_MANIFEST_FILE}" | jq -r '.files[] | (.projectID|tostring) + " " + (.fileID|tostring)'| while read -r p f
      do
        if [ ! -f $MOD_DIR/${p}_${f}.jar ]
        then
          redirect_url="$(curl -Ls -o /dev/null -w %{url_effective} ${CURSE_URL_BASE}/${p})"
          url="$redirect_url/download/${f}/file"
          log Downloading curseforge mod $url
          #  Manifest usually doesn't have mod names. Using id should be fine, tho
          curl -sSL "${url}" -o $MOD_DIR/${p}_${f}.jar
        fi
      done
    else
      log "Could not find manifest file, unsufficient privs, or malformed path."
    fi
    ;;
  *)
    log "Invalid manifest file for modpack. Please make sure it is a .json file."
    ;;
esac
fi

if [[ "${GENERIC_PACK}" ]]; then
  if isURL "${GENERIC_PACK}"; then
    generic_pack_url=${GENERIC_PACK}
    GENERIC_PACK=/tmp/$(basename ${generic_pack_url})
    log "Downloading generic pack from ${generic_pack_url} ..."
    curl -fsSL -o ${GENERIC_PACK} ${generic_pack_url}
  fi

  sum_file=/data/.generic_pack.sum
  if ! sha256sum -c ${sum_file} -s 2> /dev/null; then
    base_dir=/tmp/generic_pack_base
    mkdir -p ${base_dir}
    unzip -q -d ${base_dir} ${GENERIC_PACK}
    if [ -f /data/manifest.txt ]; then
      log "Manifest exists from older generic pack, cleaning up ..."
      while read f; do
        rm -rf "/data/${f}"
      done < /data/manifest.txt
      find /data/* -type d -exec rmdir --ignore-fail-on-non-empty {} +
      rm -f /data/manifest.txt
    fi
    log "Writing generic pack manifest ... "
    find ${base_dir} -type f -print0 | xargs -0 -I {} echo "{}" | sed "s#${base_dir}/##" > /data/manifest.txt
    log "Applying generic pack ..."
    IFS='
'
    set -f
    for d in $(find ${base_dir} -type d); do mkdir -p "$(sed "s#${base_dir}#/data#" <<< $d)"; done
    for f in $(find ${base_dir} -type f); do cp -f "$f" "$(sed "s#${base_dir}#/data#" <<< $f)"; done
    rm -rf ${base_dir}
    sha256sum ${GENERIC_PACK} > ${sum_file}
  fi
fi

exec ${SCRIPTS:-/}start-finalSetupModconfig $@
