#!/bin/bash

function isURL {
  local value=$1

  if [[ ${value:0:8} == "https://" || ${value:0:7} == "http://" ]]; then
    return 0
  else
    return 1
  fi
}

function isTrue {
  local value=${1,,}

  result=

  case ${value} in
    true|on)
      result=0
      ;;
    *)
      result=1
      ;;
  esac

  return ${result}
}

function isDebugging {
  if [[ -v DEBUG ]] && [[ ${DEBUG^^} = TRUE ]]; then
    return 0
  else
    return 1
  fi
}

function debug {
  if isDebugging; then
    log "DEBUG: $*"
  fi
}

function log {
  local n=0

  while getopts 'n' opt; do
    case $opt in
      n) n=1 ;;
    esac
  done
  shift "$(( OPTIND - 1 ))"
  
  if [ "$n" -eq 1 ]; then
    echo -n "[init] $*"
  else
    echo "[init] $*"
  fi
}
