#!/bin/bash

. ${SCRIPTS:-/}start-utils

if ! [[ -v CURSE_INSTANCE_JSON ]]; then
  log "ERROR: CURSE_INSTANCE_JSON needs to be set"
  exit 2
elif ! [ -f "${CURSE_INSTANCE_JSON}" ] && [ -f "${CURSE_INSTANCE_JSON}/minecraftinstance.json" ]; then
  CURSE_INSTANCE_JSON="${CURSE_INSTANCE_JSON}/minecraftinstance.json"
elif ! [ -f "${CURSE_INSTANCE_JSON}" ]; then
  log "ERROR: CURSE_INSTANCE_JSON file does not exist: ${CURSE_INSTANCE_JSON}"
  exit 2
fi

log "Resolved CURSE_INSTANCE_JSON as ${CURSE_INSTANCE_JSON}"

# Continue to Final Setup
exec ${SCRIPTS:-/}start-finalSetupWorld "$@"
