services:
  mc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    environment:
      EULA: "true"
      TYPE: PAPER
      MEMORY: 2G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
    restart: unless-stopped
volumes:
  mc-data: {}
