services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: "TRUE"
      TYPE: PAPER
      DEBUG: true
      PLUGINS: |
        https://download.geysermc.org/v2/projects/geyser/versions/latest/builds/latest/downloads/spigot
        https://download.geysermc.org/v2/projects/floodgate/versions/latest/builds/latest/downloads/spigot
        https://hangarcdn.papermc.io/plugins/BentoboxWorld/bentobox/versions/3.7.4/PAPER/BentoBox-3.7.4.jar
      DOWNLOAD_EXTRA_CONFIGS: |
        # Even though it's a jar can be treated just like any other file
        plugins/BentoBox/addons<https://github.com/BentoBoxWorld/AOneBlock/releases/download/1.20.0/AOneBlock-1.20.0.jar
    ports:
      - "25565:25565"
      - "25565:25565/udp"
      - "19132:19132/udp"
    volumes:
      - data:/data
volumes:
  data: