services:
  mc:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: MOHIST
      VERSION: 1.12.2
      MOHIST_BUILD: 347
    volumes:
      - data:/data

volumes:
  data: {}
