#!/bin/bash

export SERVER=paper_server.jar
if [ ! -f $SERVER ]; then
    downloadUrl=${PAPER_DOWNLOAD_URL:-https://papermc.io/api/v1/paper/${VANILLA_VERSION}/latest/download}
    echo "Downloading Paper $VANILLA_VERSION from $downloadUrl ..."
    curl -fsSL -o $SERVER "$downloadUrl"
    if [ ! -f $SERVER ]; then
      echo "ERROR: failed to download from $downloadUrl (status=$?)"
      exit 3
    fi
fi

# Normalize on Spigot for operations below
export TYPE=SPIGOT

# Continue to Final Setup
exec /start-finalSetup01World $@
