# Provides an example of running CleanroomMC from https://github.com/CleanroomMC/Cleanroom,
# which is a Forge fork
services:
  mc:
    image: itzg/minecraft-server
    ports:
    # expose the Minecraft server port outside of container
    - "25565:25565"
    environment:
      # REQUIRED for all types
      EULA: "TRUE"

      # Set server type (vs the default of vanilla)
      TYPE: CLEANROOM
      DEBUG: "true"

      # Optional (check doc for usage)
      # CLEANROOM_LOADER_VERSION: 0.0.0-alpha
      # CLEANROOM_INSTALLER_VERSION: 0.1.4
      # Using either follow env will ignore 2 above
      # CLEANROOM_FROM_LOCAL: ./installer.jar
      # CLEANROOM_FROM_URL: https://
    volumes:
    # use a named, managed volume for data volume
    - mc_data:/data
    # attach local host directory "mods" in same directory as this compose file
    # all mods in this directory get copied into /data/mods at startup
    - ./mods:/mods:ro

volumes:
  # declared the named volume, but use default/local storage engine
  mc-data: {}
