services:
  mc:
    image: itzg/minecraft-server:java8
    environment:
      EULA: "true"
      MODPACK_PLATFORM: AUTO_CURSEFORGE
      CF_SLUG: skyfactory-4
      CF_FILENAME_MATCHER: 4.2.4
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: 3G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
volumes:
  mc-data: