#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

: "${EXISTING_OPS_FILE:=SKIP}"
: "${EXISTING_WHITELIST_FILE:=SKIP}"

if [[ -v APPEND_OPS ]] && isTrue "${APPEND_OPS}"; then
  EXISTING_OPS_FILE=MERGE
elif [[ -v OVERRIDE_OPS ]] && isTrue "${OVERRIDE_OPS}"; then
  EXISTING_OPS_FILE=SYNCHRONIZE
fi

if [[ -v APPEND_WHITELIST ]] && isTrue "${APPEND_WHITELIST}"; then
  EXISTING_WHITELIST_FILE=MERGE
elif [[ -v OVERRIDE_WHITELIST ]] && isTrue "${OVERRIDE_WHITELIST}"; then
  EXISTING_WHITELIST_FILE=SYNCHRONIZE
fi

# shellcheck source=start-utils
. "${SCRIPTS:-/}start-utils"
isDebugging && set -x

sharedArgs=(--version="$VERSION")
if isFalse "${ONLINE_MODE:-true}"; then
  sharedArgs+=( --offline )
fi

if [[ -v OPS_FILE ]]; then
  mc-image-helper manage-users \
    "${sharedArgs[@]}" \
    --type=JAVA_OPS \
    --input-is-file \
    --existing="${EXISTING_OPS_FILE}" \
    "$OPS_FILE"
fi
if [[ -v OPS ]]; then
  args=()
  if isTrue "${APPEND_OPS:-false}" || isFalse "${OVERRIDE_OPS:-true}"; then
    args+=(--append-only)
  fi
  # shellcheck disable=SC2086
  mc-image-helper manage-users \
    "${sharedArgs[@]}" "${args[@]}" \
    --type=JAVA_OPS \
    --existing="${EXISTING_OPS_FILE}" \
    $OPS
fi

if [[ -v WHITELIST_FILE ]]; then
  mc-image-helper manage-users \
    "${sharedArgs[@]}" \
    --type=JAVA_WHITELIST \
    --input-is-file \
    --existing="${EXISTING_WHITELIST_FILE}" \
   "$WHITELIST_FILE"
fi
if [[ -v WHITELIST ]]; then
  args=()
  if isTrue "${APPEND_WHITELIST:-false}" || isFalse "${OVERRIDE_WHITELIST:-true}"; then
    args+=(--append-only)
  fi
  # shellcheck disable=SC2086
  mc-image-helper manage-users \
    "${sharedArgs[@]}" "${args[@]}" \
    --type=JAVA_WHITELIST \
    --existing="${EXISTING_WHITELIST_FILE}" \
    $WHITELIST
fi

exec "${SCRIPTS:-/}start-finalExec" "$@"
