#!/bin/bash

# shellcheck source=start-utils
. "$(dirname "$0")/start-utils"
isDebugging && set -x

if ! SERVER=$(mc-image-helper github download-latest-asset \
  --output-directory=/data \
  --name-pattern="NanoLimbo-.+?(?<!-sources)\.jar" \
  BoomEaro/NanoLimbo
  ); then
    logError "Failed to download NanoLimbo"
    exit 1
fi

export SERVER
export FAMILY=LIMBO

exec $(dirname "$0")/start-setupMounts "$@"
