#!/bin/bash

. ${SCRIPTS:-/}start-utils

umask 0002
chmod g+w /data

function check_if_runargs() {
  if [ -f /data/runargs.txt ]; then
    if isTrue "${RUN_FROM_ARGSFILE:=false}"; then
      if isTrue "${SETUP_ONLY:=false}"; then
          echo "RUN_FROM_ARGSFILE and SETUP_ONLY are incompatible."
          exit 1
      fi
      echo "$(</data/runargs.txt)"
    fi
  fi
}
RUN_ARGS=$(check_if_runargs)

if ! isTrue "${SKIP_SUDO:-false}" && [ $(id -u) = 0 ]; then
  runAsUser=minecraft
  runAsGroup=minecraft

  if [[ -v UID ]]; then
    if [[ $UID != 0 ]]; then
      if [[ $UID != $(id -u minecraft) ]]; then
        log "Changing uid of minecraft to $UID"
        usermod -u $UID minecraft
      fi
    else
      runAsUser=root
    fi
  fi

  if [[ -v GID ]]; then
    if [[ $GID != 0 ]]; then
      if [[ $GID != $(id -g minecraft) ]]; then
        log "Changing gid of minecraft to $GID"
        groupmod -o -g $GID minecraft
      fi
    else
      runAsGroup=root
    fi
  fi

  if [[ $(stat -c "%u" /data) != $UID ]]; then
    log "Changing ownership of /data to $UID ..."
    chown -R ${runAsUser}:${runAsGroup} /data
  fi

  if [[ ${SKIP_NSSWITCH_CONF^^} != TRUE ]]; then
    echo 'hosts: files dns' > /etc/nsswitch.conf
  fi

  if [[ -n "$RUN_ARGS" ]]; then
    exec gosu ${runAsUser}:${runAsGroup} /bin/sh -c "$RUN_ARGS"
  else
    exec gosu ${runAsUser}:${runAsGroup} ${SCRIPTS:-/}start-configuration "$@"
  fi
else
  if [[ -n "$RUN_ARGS" ]]; then
    exec /bin/sh -c "$RUN_ARGS"
  else
    exec ${SCRIPTS:-/}start-configuration "$@"
  fi
fi
