#!/bin/bash

# shellcheck source=start-utils
. "${SCRIPTS:-/}start-utils"
isDebugging && set -x

: "${FORGE_VERSION:=${FORGEVERSION:-RECOMMENDED}}"
: "${KETTING_VERSION:=}"
: "${KETTING_TAG:=${KETTING_VERSION}}"
: "${KETTING_LAUNCHER_VERSION:=1.3.0}

if [ ! -f kettinglauncher.jar ] && \
  !( \
    downloadUrl="https://github.com/kettingpowered/kettinglauncher/releases/download/v${KETTING_LAUNCHER_VERSION}/kettinglauncher-${KETTING_LAUNCHER_VERSION}.jar" || \
    downloadUrl="https://nexus.c0d3m4513r.com/repository/Ketting/org/kettingpowered/kettinglauncher/${KETTING_LAUNCHER_VERSION}/kettinglauncher-${KETTING_LAUNCHER_VERSION}.jar" \
  )
then
  log "ERROR failed to download Ketting Launcher Version ${KETTING_LAUNCHER_VERSION}?"
  exit 1
fi

if [[ $downloadUrl == null ]]; then
  log "ERROR failed to download Ketting Launcher Version ${KETTING_LAUNCHER_VERSION}?"
  log "ERROR KettingLauncher does not seem to be available for the Version ${KETTING_LAUNCHER_VERSION}"
  exit 1
 fi

if ! SERVER=$(get --output-filename --skip-up-to-date --output /data "$downloadUrl"); then
  log "ERROR: failed to download Ketting server jar from $downloadUrl"
  exit 1
fi

export SERVER
export FAMILY=HYBRID

exec "${SCRIPTS:-/}start-spiget" "$@"
