#!/bin/bash

# Possible Options: VERSION_NUMBER, latest, latest-dev
: "${GTNH_PACK_VERSION:=latest}"
: "${GTNH_DELETE_BACKUPS:=false}"
# Set server.properties defaults suitable for gtnh servers
: "${ALLOW_FLIGHT:=true}"
: "${LEVEL_TYPE:=rwg}"
: "${DIFFICULTY:=3}"
: "${ENABLE_COMMAND_BLOCK:=true}"

# shellcheck source=start-utils
. "$(dirname "$0")/start-utils"

isDebugging && set -x

ensureRemoveAllModsOff "MODPACK_PLATFORM=GTNH"

java_version=$(mc-image-helper java-release)
if [[ $java_version == 8 ]]; then
  export SERVER=/data/forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
elif [[ $java_version -ge 17 ]]; then
  export SERVER=/data/lwjgl3ify-forgePatches.jar
else 
  log "Greg Tech New Horizons only supports the following Java versions: 8, 17 or later"
  exit 2
fi

#TODO: Check if FORGE fits
export FAMILY=FORGE

exec "$(dirname "$0")/start-setupWorld" "$@"