#!/bin/bash

: "${FOLIA_CHANNEL:=default}"

# shellcheck source=start-utils
. "$(dirname "$0")/start-utils"
set -o pipefail
handleDebugMode

if [[ $FOLIA_DOWNLOAD_URL ]]; then
  export PAPER_DOWNLOAD_URL="$FOLIA_DOWNLOAD_URL"
fi

if [[ $FOLIABUILD ]]; then
  export PAPERBUILD="$FOLIABUILD"
fi

PAPER_PROJECT="folia" \
PAPER_NAME="FoliaMC" \
PAPER_CHANNEL="${FOLIA_CHANNEL}" \
  exec "$(dirname "$0")/start-deployPaper" "$@"
