#!/bin/bash

set -e -o pipefail

: "${VANILLATWEAKS_FILE:=}"
: "${VANILLATWEAKS_SHARECODE:=}"

# shellcheck source=start-utils
. "${SCRIPTS:-/}start-utils"

if [[ ${VANILLATWEAKS_FILE} || ${VANILLATWEAKS_SHARECODE} ]]; then
  mc-image-helper vanillatweaks \
    --output-directory="/data" \
    --world-subdir="${LEVEL:-world}" \
    --share-codes="$VANILLATWEAKS_SHARECODE" \
    --pack-files="$VANILLATWEAKS_FILE"
fi

exec "${SCRIPTS:-/}start-setupDatapack" "$@"
