#!/bin/bash

# shellcheck source=start-utils
. "${SCRIPTS:-/}start-utils"
isDebugging && set -x

: "${FORGE_VERSION:=${FORGEVERSION:-RECOMMENDED}}"
: "${MAGMA_MAINTAINED_TAG:=}"

resolveVersion

if ! downloadUrl="https://github.com/magmamaintained/Magma-${VERSION}/releases/download/${MAGMA_MAINTAINED_TAG}/magma-${VERSION}-${FORGE_VERSION}-${MAGMA_MAINTAINED_TAG}-server.jar"; then
  log "ERROR failed to locate latest Magma Maintained download for ${VERSION}, ${FORGE_VERSION}, and ${MAGMA_MAINTAINED_TAG}. Is that version supported?"
  exit 1
fi

if [[ $downloadUrl == null ]]; then
  log "ERROR Magma Maintained does not seem to be available for $VERSION"
  exit 1
fi

if ! SERVER=$(get --output-filename --skip-up-to-date --output /data "$downloadUrl"); then
  log "ERROR: failed to download Magma Maintained server jar from $downloadUrl"
  exit 1
fi

export SERVER
export FAMILY=HYBRID

exec "${SCRIPTS:-/}start-spiget" "$@"
