#!/bin/bash

# shellcheck source=start-utils
. "${SCRIPTS:-/}start-utils"

# The Dockerfile ENVs take precedence here, but defaulting for testing consistency
: "${UID:=1000}"
: "${GID:=1000}"
: "${UID_SERVICE:=1001}"
: "${GID_SERVICE:=1001}"
: "${SKIP_CHOWN_DATA:=false}"
export UID GID UID_SERVICE GID_SERVICE

umask "${UMASK:=0002}"

# Remove from previous run and do this as elevated user since file used to be created before demoting
rm -f "$HOME/.rcon-cli.env"

if ! isTrue "${SKIP_SUDO:-false}" && [ "$(id -u)" = 0 ]; then
  runAsUser=service-account
  runAsGroup=service-group

  if [[ -v UID_SERVICE ]]; then
    if [[ $UID_SERVICE != 0 ]]; then
      if [[ $UID_SERVICE != $(id -u service-account) ]]; then
        log "Changing uid of service-account to $UID_SERVICE"
        usermod -u $UID_SERVICE service-account
      fi
    else
      runAsUser=root
    fi
  fi

  if [[ -v GID_SERVICE ]]; then
    if [[ $GID_SERVICE != 0 ]]; then
      if [[ $GID_SERVICE != $(id -g service-account) ]]; then
        log "Changing gid of service-group to $GID_SERVICE"
        groupmod -o -g "$GID_SERVICE" service-account
      fi
    else
      runAsGroup=root
    fi
  fi

  if [[ ${SKIP_NSSWITCH_CONF^^} != TRUE ]]; then
    echo 'hosts: files dns' > /etc/nsswitch.conf
  fi
fi
"${SCRIPTS:-/}start-configuration" "$@"