services:
  minecraft:
    image: itzg/minecraft-server
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      TYPE: NEOFORGE
      VERSION: "1.20.4"
      # Include Connector mod to enable Fabric mod compatibility on NeoForge
      MODRINTH_PROJECTS: |
        connector
        fabric-api
        # sodium is a client-side rendering mod and will be ignored on the server
        sodium
        lithium
        # iris is a client-side rendering mod and will be ignored on the server
        iris
    volumes:
      - ./data:/data
    restart: unless-stopped
    tty: true
    stdin_open: true
