services:
  mc:
    image: itzg/minecraft-server
    environment:
      EULA: true
      # https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/
      MODPACK_PLATFORM: AUTO_CURSEFORGE
#      CF_PAGE_URL: https://www.curseforge.com/minecraft/modpacks/skyfactory-5/files/6044634
      CF_SLUG: skyfactory-5
      CF_FILENAME_MATCHER: 5.0.2
      # Allocate API key from https://console.curseforge.com/
      # and set in .env file making sure to double up dollar signs, such as
      # CF_API_KEY=$$2a$$10$$....
      # Refer to https://docker-minecraft-server.readthedocs.io/en/latest/types-and-platforms/mod-platforms/auto-curseforge/#api-key
      CF_API_KEY: ${CF_API_KEY}
      MEMORY: 4G
    ports:
      - "25565:25565"
    volumes:
      - mc-data:/data
volumes:
  mc-data:
