name: Auto release
on:
  schedule:
    - cron: "0 14 * * *"
  workflow_dispatch:
jobs:
  auto-release:
    runs-on: ubuntu-latest
    # If forked, changed to your username to enable auto-releases
    if: github.repository_owner == 'itzg'
    permissions:
      # allow for creating releases/tags
      contents: write
    steps:
      - uses: zenengeo/github-auto-release-action@main
        with:
          stable-duration: 3d
          force-duration: 14d  
